### ISSUE TITLE
#Deploy Error 

### ISSUE THREAD

**Issue by DarkenWaves** [lyfe00011/whatsapp-bot-md#105]
I cant Deploy Bot #error

**Comment by lyfe00011** [comment]
> I cant Deploy Bot #error

Where

**Comment by jisahanx2** [comment]
Hlo

**Comment by 55ckc** [comment]
I cant see the heroku page after taping fork and deploy and puting my github username

**Comment by lyfe00011** [comment]
> I cant see the heroku page after taping fork and deploy and puting my github username

Screen shot
