### ISSUE TITLE
suggest hosting on vps

### ISSUE THREAD

**Issue by pengengantibaju** [lyfe00011/whatsapp-bot-md#11]
hello any idea how to deploy in vps because heroku still suspending

**Comment by lyfe00011** [comment]
> hello any idea how to deploy in vps because heroku still suspending

you can git clone, install dependencies and run

**Comment by lyfe00011** [comment]
> how about a database ? there no database ?

It's ok will creates a local one

**Comment by simo12341** [comment]
.song 
.apk
.yts

**Comment by imacrosid** [comment]
hi , i go this error what should i do ? 

> G:\Learning\whatsapp-bot-md>node index.js
> levanter 3.5.8
> Database syncing...
> TypeError: _0x35dc38 is not a function
>     at _0x4da819.connect (G:\Learning\whatsapp-bot-md\lib\client.js:1:57472)
>     at async start (G:\Learning\whatsapp-bot-md\index.js:9:3)
