### ISSUE TITLE
Used file taking too much storage

### ISSUE THREAD

**Issue by xon54** [lyfe00011/whatsapp-bot-md#112]
So actually any way to auto remove file after upload it to whatspp? Like when i get some using (play,song,YouTube, twitter) upload done but in my vm still keep it so am asking its possible to to auto remove after upload done?
Thanks you

**Comment by lyfe00011** [comment]
> So actually any way to auto remove file after upload it to whatspp? Like when i get some using (play,song,YouTube, twitter) upload done but in my vm still keep it so am asking its possible to to auto remove after upload done? Thanks you

Hmm wait

**Comment by xon54** [comment]
Thanks

**Comment by Machee786** [comment]
> So actually any way to auto remove file after upload it to whatspp? Like when i get some using (play,song,YouTube, twitter) upload done but in my vm still keep it so am asking its possible to to auto remove after upload done?
> Thanks you
