### ISSUE TITLE
termux

### ISSUE THREAD

**Issue by innocentkiller22** [lyfe00011/whatsapp-bot-md#128]
can i make bot on termux . If yes . how can i

**Comment by lyfe00011** [comment]
with ubuntu 
install node,yarn,pm2,ffmpeg
npm start

**Comment by SHI208** [comment]
_**yes**_

**Comment by MininxD** [comment]
> can i make bot on termux . If yes . how can i

yes, just install nodejs 16.x and ffmpeg
`$ pkg install nodejs-lts`
`$ pkg install ffmpeg`

and git clone this repo and install
`$ npm install`
next step just run
