### ISSUE TITLE
can you add ,vote and filter commands?

### ISSUE THREAD

**Issue by nexusNw** [lyfe00011/whatsapp-bot-md#13]

**Comment by lyfe00011** [comment]
done

**Comment by nexusNw** [comment]
![Screenshot_20220612-220146](https://user-images.githubusercontent.com/88531428/173243346-9f31e18e-a01b-4d7c-b3dc-91306b8d6c8f.png)


instead of this repeatedly Coming , can you make vote with taging everyone🙂
