### ISSUE TITLE
npm not started In termex linux

### ISSUE THREAD

**Issue by innocentkiller22** [lyfe00011/whatsapp-bot-md#135]
![Screenshot_20221008-073114](https://user-images.githubusercontent.com/112341377/194682736-0971854b-133a-4cb1-9fa6-7a0625e5ae54.png)

**Comment by lyfe00011** [comment]
What are you doing 🙄

**Comment by PADDYGUPTA301175** [comment]
trying to make bot in linux

**Comment by lyfe00011** [comment]
> trying to make bot in linux

1 install git,ffmpeg, pm2,yarn
2 git clone repo
3 cd 
4 yarn 
5 nano config.env ( add sticker, session,prefix var,...)
6 npm start
