### ISSUE TITLE
I m adding my own Modified Files in Plugins as Extrenal Plugins But when Bot Restart My FIles Are Remove and Not Work

### ISSUE THREAD

**Issue by zainiprince** [lyfe00011/whatsapp-bot-md#139]
**I m adding my own Modified Files in Plugins as Extrenal Plugins But when Bot Restart My FIles Are Remove and Not Work******

**Comment by lyfe00011** [comment]
> **I m adding my own Modified Files in Plugins as Extrenal Plugins But when Bot Restart My FIles Are Remove and Not Work******

For now use gist link and install it using plugin cmd
