### ISSUE TITLE
need new upload plungin for upload more than 1gb file less than 2gb

### ISSUE THREAD

**Issue by CP2003** [lyfe00011/whatsapp-bot-md#144]
I need upload some files to my group members ,but bot cant upload that ,plz help

**Comment by lyfe00011** [comment]
> I need upload some files to my group members ,but bot cant upload that ,plz help

what you mean bot cant

**Comment by CP2003** [comment]
> 

bot can't upload file more than 1gb

**Comment by lyfe00011** [comment]
> > 
> 
> bot can't upload file more than 1gb only 110mb file can uploaded

If your using heroku , use a plan that can handle 1 gb file

**Comment by lyfe00011** [comment]
> > If your using heroku , use a plan that can handle 1 gb file
> 
> * then I deploy on railway ,can I upload 1Gb file

It not depends what platform. It's all what you have.
