### ISSUE TITLE
sudo

### ISSUE THREAD

**Issue by PADDYGUPTA301175** [lyfe00011/whatsapp-bot-md#152]
following not working in google cloud
1. sudo
2. i cant change PREFIX
3. i cant change name on sticker

**Comment by lyfe00011** [comment]
> following not working in google cloud
> 
> 1. sudo
> 2. i cant change PREFIX
> 3. i cant change name on sticker

did you created confg.env ?

**Comment by PADDYGUPTA301175** [comment]
yes
