### ISSUE TITLE
How to handle this

### ISSUE THREAD

**Issue by revanapriyandi** [lyfe00011/whatsapp-bot-md#163]
**Describe the bug**
Can't run on windows 11

**To Reproduce**
1. Go to 'npm start'
2. See error

**Expected behavior**
how can this run on my windows?

**Screenshots**
![image](https://user-images.githubusercontent.com/44662937/206708215-65897bae-3440-46f4-87fd-8ca2cc8c317a.png)

**Platform (please complete the following information):**
 - Platform: Windows 11
 - Version 4.0.2

**Additional context**
I have followed the deploy in pc example
![image](https://user-images.githubusercontent.com/44662937/206708438-65e70e9b-71fa-44d9-a709-ac5e0f0a8f00.png)

**Comment by lyfe00011** [comment]
hmm windows
