### ISSUE TITLE
Instagram Reels Not Downloading, saying " NOT FOUND ". Even if reel is there

### ISSUE THREAD

**Issue by Akashtailor-exe** [lyfe00011/whatsapp-bot-md#166]
**Describe the bug**
using !insta command, while i am trying to download reels. some reels are not downloading and saying not found. many reels are not downloading. this error is coming in almost every links

**To Reproduce**

**Expected behavior**
need the video

**Screenshots**
i am giving some Instagram reel link. you can click open it on Instagram, it is there also it is a public account.
but while using !insta command these reels are not downloading
you can try using !insta command yourself
https://www.instagram.com/reel/CmAFKaAu-WC/?igshid=YmMyMTA2M2Y=
https://www.instagram.com/reel/CmEdeNBoeE8/?igshid=YmMyMTA2M2Y=
https://www.instagram.com/reel/CkkAe0GI6E5/?igshid=YmMyMTA2M2Y=
https://www.instagram.com/reel/CkUa8cZLyVj/?igshid=YmMyMTA2M2Y=

**Platform (please complete the following information):**
 - Platform: koyeb
 - Version 4.0.3

**Additional context**

**Comment by lyfe00011** [comment]
![Uploading Screenshot_2022-12-16-13-40-50-860_com.whatsapp.jpg…]()

**Comment by lyfe00011** [comment]
![Screenshot_2022-12-16-13-40-50-860_com whatsapp](https://user-images.githubusercontent.com/76509367/208053590-6273faa3-7df8-4273-88b6-87bc24611654.jpg)
