### ISSUE TITLE
Insta feature not working

### ISSUE THREAD

**Issue by harshitkamboj** [lyfe00011/whatsapp-bot-md#17]
.insta is not working on every link and every time it show not found, pls fix it :D

**Comment by kaannerden33** [comment]
Gönderme bana ileti
________________________________
From: harshitkamboj ***@***.***>
Sent: Wednesday, June 8, 2022 2:58:49 PM
To: lyfe00011/whatsapp-bot-md ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lyfe00011/whatsapp-bot-md] Insta feature not working (Issue #17)


.insta is not working on every link and every time it show not found, pls fix it :D
