### ISSUE TITLE
cbutton or url button doesn't work please fix it

### ISSUE THREAD

**Issue by nep-goloapp** [lyfe00011/whatsapp-bot-md#171]
**Describe the bug**

**To Reproduce**
1. Go to '.alive https://i.imgur.com/33MpPJ8.jpeg *Wishing You Happy New Year*#ubutton\url name# #url\button url#
#button\button# #header\header#
#cbutton\cbutton# #num\91876543210#'

2. whenever we use cbutton or ubutton then .alive replies to the same registered number only. 

3. Click on '.alive'

4. Scroll down to '.alive replies to the same sender number'
 
5. See error
whenever we use cbutton or ubutton then .alive replies to the same registered number only. 

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Platform: koyeb.com
 - Version 

**Additional context**
whenever we use cbutton or ubutton then .alive replies to the same registered number only. 
![IMG_20221224_175157](https://user-images.githubusercontent.com/121329649/209435449-296e9e45-a083-4c09-9f50-a8edd7c7cc80.jpg)

**Comment by lyfe00011** [comment]
that is a expected behaviour

**Comment by nep-goloapp** [comment]
Yes i thought so, but checked many times.

Whenever i use #ubtton or #cbutton then .alive command reply to my same
registered number only. But if i use normal #button command it works with
all user number.

Please check once and help me.

**Comment by nep-goloapp** [comment]
> that is a expected behaviour

Yes i thought so, but checked many times. 

Whenever i use #ubtton or #cbutton then .alive command reply to my same registered number only. But if i use normal #button command it works with all user number.

Please check once and help me.
Hide quoted text
