### ISSUE TITLE
Didn't get the session 

### ISSUE THREAD

**Issue by MxxnKnight** [lyfe00011/whatsapp-bot-md#190]
The session getting as
"Waiting for this message.this may take while."

My whatsapp is letest version
![IMG_20230228_213450](https://user-images.githubusercontent.com/91146761/221909859-0ee990a2-1466-4e7c-8793-972056a4deb5.jpg)

**Comment by lyfe00011** [comment]
u can copy id from qr page

**Comment by MxxnKnight** [comment]
The logged device was sleeping after some time

![IMG_20230301_001342](https://user-images.githubusercontent.com/91146761/221949034-a43621c3-27d7-407a-95be-e5b69cdbe828.jpg)

**Comment by lyfe00011** [comment]
so

**Comment by MxxnKnight** [comment]
The bot is not responding quickly.sometimes doesn't,sometimes hours later

**Comment by lyfe00011** [comment]
it depends where you hosted.

**Comment by MxxnKnight** [comment]
Logs

**Comment by MxxnKnight** [comment]
LOGS picture
