### ISSUE TITLE
Add render.com deploy

### ISSUE THREAD

**Issue by Arian03dc** [lyfe00011/whatsapp-bot-md#194]
Hello, dev!!:
I'm from Cuba, and in this country the credit cards are forbidden. I can't deploy your bot bcz I don't  have credit card, and using VPN fails. I think that adding deploy to render.com website fix this neccesity. I successfully deployed some bots on this website. Thanks a lot for read my comment!!!!

**Comment by diamon448** [comment]
Thank you

**Comment by diamon448** [comment]
Render.com deploy

**Comment by lyfe00011** [comment]
it is super slow
