### ISSUE TITLE
Windows Instance

### ISSUE THREAD

**Issue by kamrankhoxa** [lyfe00011/whatsapp-bot-md#208]
**Describe the bug**
$ npm start

> ustad@4.3.5 start
> pm2 start . --attach --namespace Ustad --name Ustad --time

[PM2] Applying action restartProcessId on app [.](ids: [ 0 ])
[PM2] [Ustad](0) ✓
[PM2] Process successfully started
┌─────┬──────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name     │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ Ustad    │ Ustad       │ 4.3.5   │ fork    │ 4608     │ 1s     │ 6    │ online    │ 0%       │ 59.9mb   │ Adminis… │ disabled │
└─────┴──────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
[PM2][INFO] Log streaming apps id: 0, exit with Ctrl-C or will exit in 10secs
0|Ustad  | 2023-04-09T21:33:35: TypeError: _0x3ec6f8[("wri" + _0x44fc43(...) + "tre" + "am")] is not a function
0|Ustad  | 2023-04-09T21:33:35:     at Object.<anonymous> (C:\Users\Administrator\Desktop\Bot\lib\handle.js:1:63671)
0|Ustad  | 2023-04-09T21:33:35:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
0|Ustad  | 2023-04-09T21:33:35:     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
0|Ustad  | 2023-04-09T21:33:35:     at Module.load (node:internal/modules/cjs/loader:1117:32)
0|Ustad  | 2023-04-09T21:33:35:     at Module._load (node:internal/modules/cjs/loader:958:12)
0|Ustad  | 2023-04-09T21:33:35:     at Module.require (node:internal/modules/cjs/loader:1141:19)
0|Ustad  | 2023-04-09T21:33:35:     at Hook._require.Module.require (C:\Users\Administrator\Desktop\Bot\node_modules\require-in-the-middle\index.js:101:39)
0|Ustad  | 2023-04-09T21:33:35:     at require (node:internal/modules/cjs/helpers:110:18)
0|Ustad  | 2023-04-09T21:33:35:     at Object.<anonymous> (C:\Users\Administrator\Desktop\Bot\lib\client.js:1:16006)
0|Ustad  | 2023-04-09T21:33:35:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
PM2      | App [Ustad:0] exited with code [1] via signal [SIGINT]
PM2      | App [Ustad:0] starting in -fork mode-
PM2      | App [Ustad:0] online
0|Ustad  | 2023-04-09T21:33:43: TypeError: _0x3ec6f8[("wri" + _0x44fc43(...) + "tre" + "am")] is not a function
0|Ustad  | 2023-04-09T21:33:43:     at Object.<anonymous> (C:\Users\Administrator\Desktop\Bot\lib\handle.js:1:63671)
0|Ustad  | 2023-04-09T21:33:43:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
0|Ustad  | 2023-04-09T21:33:43:     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
0|Ustad  | 2023-04-09T21:33:43:     at Module.load (node:internal/modules/cjs/loader:1117:32)
0|Ustad  | 2023-04-09T21:33:43:     at Module._load (node:internal/modules/cjs/loader:958:12)
0|Ustad  | 2023-04-09T21:33:43:     at Module.require (node:internal/modules/cjs/loader:1141:19)
0|Ustad  | 2023-04-09T21:33:43:     at Hook._require.Module.require (C:\Users\Administrator\Desktop\Bot\node_modules\require-in-the-middle\index.js:101:39)
0|Ustad  | 2023-04-09T21:33:43:     at require (node:internal/modules/cjs/helpers:110:18)
0|Ustad  | 2023-04-09T21:33:43:     at Object.<anonymous> (C:\Users\Administrator\Desktop\Bot\lib\client.js:1:16006)
0|Ustad  | 2023-04-09T21:33:43:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
PM2      | App [Ustad:0] exited with code [1] via signal [SIGINT]
PM2      | App [Ustad:0] starting in -fork mode-
PM2      | App [Ustad:0] online

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/47171583/230797551-e889158c-6882-4196-b85f-37309fedda3e.png)

**Platform (please complete the following information):**
 - Platform: [Windows RDP]
 - Version [Win 10]

**Additional context**

**Comment by lyfe00011** [comment]
sync
