### ISSUE TITLE
.plugin is not working !!

### ISSUE THREAD

**Issue by abdessattar23** [lyfe00011/whatsapp-bot-md#217]
**.plugin command is not working**
The plugin command to add new plugins to the bot is not working, it returns **Not found** for every existing plugin.

**To Reproduce**
1. Type **.plugin** + **The link of a plugin**
2. See the error.

**Platform (please complete the following information):**
 - Platform: Koyeb
 - Version : I don't know.

**Comment by lyfe00011** [comment]
where id error

**Comment by abdessattar23** [comment]
You mean 'where is the error' the error is that I can't add plugins

**Comment by lyfe00011** [comment]
U can produce screenshot
