### ISSUE TITLE
How to create your plugin with the help of chatgpt

### ISSUE THREAD

**Issue by Tarkiin** [lyfe00011/whatsapp-bot-md#223]
I would like to know how to create your own plugins, I know some programming along with gpt would be helpful

And tried to create a simple plugin but it doesn't work what is the problem?
When writing test it should send the image, but it doesn't work
.plugin https://gist.githubusercontent.com/Tarkiin/b5cd2066110c43212756fc1cb523428a/raw/82e35bcd04688ae4c5f7b3175eb9eb0f4bc6bb6a/prueba.js

``
const { bot } = require('../lib/');

bot(
  {
    pattern: 'prueba',
    fromMe: true,
    desc: 'Send image plugin',
    type: 'misc',
  },
  async (message) => {
    const imageUrl = 'https://i.pinimg.com/736x/89/96/d2/8996d212b2cb35d5fc18898a78cad391--heart-love.jpg'; // Reemplaza 'URL_DE_LA_IMAGEN_AQUI' con la URL de la imagen que deseas enviar
    const options = {
      caption: 'Imagen de prueba', // Opcional: Puedes agregar un pie de foto a la imagen
    };

    return await message.sendImage({ url: imageUrl }, options);
  }
);
``

**Comment by lyfe00011** [comment]
```
const { bot } = require('../lib/')

bot(
	{
		pattern: 'prueba',
		fromMe: true,
		desc: 'Send image plugin',
		type: 'misc',
	},
	async (message) => {
		const imageUrl =
			'https://i.pinimg.com/736x/89/96/d2/8996d212b2cb35d5fc18898a78cad391--heart-love.jpg' // Reemplaza 'URL_DE_LA_IMAGEN_AQUI' con la URL de la imagen que deseas enviar
		const options = {
			caption: 'Imagen de prueba', // Opcional: Puedes agregar un pie de foto a la imagen
		}

		return await message.sendFromUrl(imageUrl, options)
	}
)
```
