### ISSUE TITLE
brooh🙂

### ISSUE THREAD

**Issue by tearpc** [lyfe00011/whatsapp-bot-md#25]
Can i take this script , to make a new bot by moding some files?

**Comment by its-me-master** [comment]
@

**Comment by its-me-master** [comment]
![Uploading IMG_20220628_000415_874.jpg…]()

**Comment by its-me-master** [comment]
- 🌺ɪͥᴛͭsᷤ ͢_͢**͢ᴍͫᴇͤᡃ⃝M𝐌Δ𝐒𝐓Ξ𝐑🕊️**_

**Comment by its-me-master** [comment]
. Tag
