### ISSUE TITLE
how to tag all but not admins ?

### ISSUE THREAD

**Issue by akhtarbalouch** [lyfe00011/whatsapp-bot-md#251]

**Comment by akhtarbalouch** [comment]
thanks i found .tag notadmin

**Comment by akhtarbalouch** [comment]
but  ".setcmd tag notadmin text "
setting sticker doesnt work
it also includes admins and notadmin command too

**Comment by Drogbha** [comment]
Helli

**Comment by lyfe000117** [comment]
Hey user.

**Comment by EMM523** [comment]
How to setcookie bing

**Comment by Francicy** [comment]
Powa

**Comment by Francicy** [comment]
thanks i found .tag notadmin

**Comment by Mohdegai** [comment]
I need a WhatsApp bot please 🥺
