### ISSUE TITLE
Koyeb deployment not working

### ISSUE THREAD

**Issue by mubeenkh4u** [lyfe00011/whatsapp-bot-md#272]
**Describe the bug**
When deploying on koyeb, error is giving during build process and subsequently deployment is stopped.

**To Reproduce**
1. Deploy as per instructions on github
2. Go to information tab (where build information is being logged).
3. Scroll down to bottom, error msg will appear.

**Expected behavior**
Deployment should work, but it is not working.

**Screenshots**

**Platform (please complete the following information):**
 - Platform: Koyeb
 - Version Latest

**Additional context**

**Comment by lyfe00011** [comment]
what kind of issue facedd ?

**Comment by lyfe00011** [comment]
Thanks
