### ISSUE TITLE
Google 

### ISSUE THREAD

**Issue by hive-sammie** [lyfe00011/whatsapp-bot-md#281]
Please I need real google, and can I DM you 🙏🙏

**Comment by lyfe00011** [comment]
You can use bing and jean

**Comment by hive-sammie** [comment]
> You can use bing and jean

I don't have pc presently and jean in not complex

**Comment by lyfe00011** [comment]
Bing within bot itself

**Comment by hive-sammie** [comment]
I don't have pc unless you know a way to collect cookies from the phone??

**Comment by weskerty** [comment]
> I don't have pc unless you know a way to collect cookies from the phone??

You can install [Termux](https://github.com/termux/termux-app/releases)
Then[ install Debian within Termux](https://github.com/wahasa/Debian) and LXDE as Environment. Open Firefox and follow the same procedure.

**Comment by lyfe00011** [comment]
https://whatsapp.com/channel/0029Va92msU59PwYuplVMH2L

Please check Last messages
