### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by innocentkiller22** [lyfe00011/whatsapp-bot-md#286]
I develop bot on ubuntu using UserLand. But it stop after some days . i used pm2 start bot name . it shows online . bot not accepting and commands
![Uploading WhatsApp Image 2023-11-23 at 10.21.50 AM.jpeg…]()

**Comment by PADDYGUPTA301175** [comment]
Same problem again 
![Uploading Screenshot_20231126-221124.png…]()
