### ISSUE TITLE
Error - Install with script

### ISSUE THREAD

**Issue by PADDYGUPTA301175** [lyfe00011/whatsapp-bot-md#287]
Install with script
![Screenshot_20231123-202715](https://github.com/lyfe00011/whatsapp-bot-md/assets/114812591/6bd71c67-7000-47db-84e2-b20428457945)
 . I fond error. Linux in userland

**Comment by lyfe00011** [comment]
https://stackoverflow.com/questions/35821245/github-server-certificate-verification-failed
