### ISSUE TITLE
Issue In QR Scan

### ISSUE THREAD

**Issue by saramkhani** [lyfe00011/whatsapp-bot-md#29]
QR scan Nnt working
Error showing " Bad Request"

**Comment by kaannerden33** [comment]
do not send me mail
________________________________
From: SaramX ***@***.***>
Sent: Saturday, June 25, 2022 8:15:12 PM
To: lyfe00011/whatsapp-bot-md ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lyfe00011/whatsapp-bot-md] Issue In QR Scan (Issue #29)


QR scan Nnt working
Error showing " Bad Request"
