### ISSUE TITLE
Docker build not working

### ISSUE THREAD

**Issue by amegh-amz** [lyfe00011/whatsapp-bot-md#290]
trying to deploy the bot using docker but its not getting deployed 

this is the error im getting

Nov 25 02:40:05 PM  Your service is live 🎉
Nov 25 02:40:00 PM  0|levanter  | [09:09:59.647] INFO (40): levanter 5.1.5
Nov 25 02:40:01 PM  0|levanter  | [09:10:01.218] INFO (40): Database syncing...
Nov 25 02:40:05 PM  0|levanter  | 10000
Nov 25 02:40:05 PM  0|levanter  | [09:10:05.020] INFO (40): Initiating New AuthState.
Nov 25 02:40:05 PM  0|levanter  | [09:10:05.020] WARN (40): Invalid AuthState!
Nov 25 02:40:06 PM  0|levanter  | pm2 stoping instance undefined
Nov 25 02:40:06 PM  PM2         | Stopping app:levanter id:0
Nov 25 02:40:06 PM  PM2         | pid=40 msg=failed to kill - retrying in 100ms
Nov 25 02:40:06 PM  PM2         | App [levanter:0] exited with code [0] via signal [SIGINT]
Nov 25 02:40:06 PM  PM2         | pid=40 msg=process killed

**Comment by lyfe00011** [comment]
Missing session id
