### ISSUE TITLE
script not found

### ISSUE THREAD

**Issue by PADDYGUPTA301175** [lyfe00011/whatsapp-bot-md#291]
I develop bot ( with script )on ubuntu using UserLand. But it stop after some days . i used pm2 start bot name. It says script not found

**Comment by lyfe00011** [comment]
Screenshot?

**Comment by PADDYGUPTA301175** [comment]
Problem solved. But it not working 
![Screenshot_20231126-221124](https://github.com/lyfe00011/whatsapp-bot-md/assets/114812591/ee8bdb65-4e4f-43b1-b49e-f0f854c6d08a)
Not accepting comands

**Comment by lyfe00011** [comment]
Check log

**Comment by PADDYGUPTA301175** [comment]
I don't understand

**Comment by PADDYGUPTA301175** [comment]
I had error in log. How to remove

**Comment by lyfe00011** [comment]
What is it
