### ISSUE TITLE
INVALID SESSION ID SCAN AGAIN 

### ISSUE THREAD

**Issue by baduseruyir** [lyfe00011/whatsapp-bot-md#311]
**Describe the bug**

**To Reproduce**
1. Go to 'logs'
5. [PM2][INFO] Log streaming apps id: 0, exit with Ctrl-C or will exit in 10secs
0|levanter  | [19:57:28.266] INFO (40): levanter 5.1.7
0|levanter  | [19:57:29.060] INFO (40): Database syncing...
0|levanter  | false
0|levanter  | 3000
0|levanter  | [19:57:32.664] INFO (40): Initiating New AuthState.
0|levanter  | [19:57:32.664] INFO (40): loading auth file
0|levanter  | [19:57:32.913] ERROR (40): {"error":"```status : 404\nreason : Not Found\nurl : 25_12_24e8_0a92_f7f1```"}
0|levanter  | 25_12_24e8_0a92_f7f1 INVALID SESSION ID, SCAN AGAIN!!!
0|levanter  | 25_12_24e8_0a92_f7f1 INVALID SESSION ID, SCAN AGAIN!!!
0|levanter  | 25_12_24e8_0a92_f7f1 INVALID SESSION ID, SCAN AGAIN!!!
0|levanter  | 
0|levanter  | [19:57:32.914] WARN (40): Invalid AuthState!
0|levanter  | pm2 stoping instance undefined
PM2         | Stopping app:levanter id:0
PM2         | App [levanter:0] exited with code [0] via signal [SIGINT]
PM2         | pid=40 msg=process killed

**Expected behavior**
Service has started. 

**Screenshots**
![Screenshot_20231225_014311](https://github.com/lyfe00011/whatsapp-bot-md/assets/100788930/791f637e-0159-4593-a2c5-4df2ebade260)

**Platform (please complete the following information):**
 - Platform: RENDER
 - Version LATEST 

**Additional context**

**Comment by weskerty** [comment]
You must start with a phone number and quickly start the bot
