### ISSUE TITLE
Bot not working for others

### ISSUE THREAD

**Issue by baduseruyir** [lyfe00011/whatsapp-bot-md#313]
Bot is not working for others who aren't sudo. I'll send you the screenshot also.. What should I do? 
Is there any env variable for making it public.? 
![Screenshot_20231226_185105](https://github.com/lyfe00011/whatsapp-bot-md/assets/100788930/d379f4ac-9fa5-446e-8b97-aed5b30c6709)
![Screenshot_20231226_185110](https://github.com/lyfe00011/whatsapp-bot-md/assets/100788930/ef127651-ff57-4f49-94ba-9f2cc54a46d2)

**Comment by weskerty** [comment]
Send .list AND READ each function.
Only sudos can control the bot. To add sudo to someone you must quote their message with the .setsudo command. This will give that person full control of the bot.

If you want a group or person to have only specific permissions, you must send .zushi and the command to use. Example .zushi gpt, there the whole group can use only gpt.

Before asking these questions, read.

**Comment by baduseruyir** [comment]
Everyone need to use every function,  what to do?

**Comment by weskerty** [comment]
> Everyone need to use every function, what to do?

Sure?
If everyone can use all the features then everyone could ban, reboot, or overwhelm the bot.

If you want to add all the functions in a group send `.zushi gpt sticker cs qc`... and all the other commands you need.

**Comment by baduseruyir** [comment]
Bro I mean not all, I mean that only utility, download, edits etc. what I
can do?

**Comment by lyfe00011** [comment]
cmd `zushi` helps you

**Comment by baduseruyir** [comment]
Writing all needed cmds are boring and time consuming. Make env var MODE = public
Deploying the bot only for me is not making sense.

**Comment by lyfe00011** [comment]
If you can't spend a minute better don't try this one.

**Comment by weskerty** [comment]
> Make env var MODE = public Deploying the bot only for me is not making sense.

If many send you messages or you exceed 250 messages sent every so often, WhatsApp will block your account.  Remember that bots are prohibited on WhatsApp.
