### ISSUE TITLE
Status send to pm problem/when we make status view "true"it send all status in our "PM" kindly help me solve this problem 

### ISSUE THREAD

**Issue by bilalking99** [lyfe00011/whatsapp-bot-md#315]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Platform: [e.g. Heroku]
 - Version [e.g. 3.4.5]

**Additional context**

**Comment by lyfe00011** [comment]
https://github.com/lyfe00011/whatsapp-bot-md/wiki/Environment_Variables

**Comment by bilalking99** [comment]
How to stop this please help

**Comment by lyfe00011** [comment]
status off
