### ISSUE TITLE
Bot stops working sometimes (more than 30+ times a day)

### ISSUE THREAD

**Issue by baduseruyir** [lyfe00011/whatsapp-bot-md#319]
**Describe the bug**
I am using render to deploy. The bot deploy well and all plugins are installed. But the problem is the bot will stop working sometimes. There's no error displaying in the log or WhatsApp. The boat doesn't even ping. 
I want to deploy the bot once again to make it working. 

**To Reproduce**
1. Go to Render
2. Deploy lyfe-MD 
3. Set cron job or uptimerobot for keeping it away from spin down
4. After some time bot will stop working. 

**Expected behavior**
Bot should work normally. 

**Screenshots**

![Screenshot_20231230_214301](https://github.com/lyfe00011/whatsapp-bot-md/assets/100788930/c761c712-d415-4ef2-b638-e80fd3c444d2)
![Screenshot_20231230_215120](https://github.com/lyfe00011/whatsapp-bot-md/assets/100788930/6a42f327-fbe5-44a1-80fd-c7d5da7095cc)

**Platform (please complete the following information):**
 - Platform: Render
 - Version Latest

**Additional context**
It'll be much helpful if you solve my problem ☺️

**Comment by lyfe00011** [comment]
It depends platform configuration, please check what you have with free plan

**Comment by baduseruyir** [comment]
Any other deploying ways for free
