### ISSUE TITLE
Deploy link isn't working anymore 😪

### ISSUE THREAD

**Issue by Mayorpromise** [lyfe00011/whatsapp-bot-md#337]

**Comment by weskerty** [comment]
Dude, give more context. Complete the Template.

**Comment by Mayorpromise** [comment]
THE DEPLOY LINK FOR HERUKO PLATFORM ISN'T WORKING AGAIN, IT SHOWS AND ERROR MESSAGE.
![Screenshot_2024-01-14-06-08-32-979_com android chrome](https://github.com/lyfe00011/whatsapp-bot-md/assets/154396061/5694fe1c-c164-4557-8b34-82de803bc780)

**Comment by Mayorpromise** [comment]
IT SHOWS PAGE NOT FOUND
WHICH MEANS I CAN'T DEPLOY ON HERUKO ANYMORE.

**Comment by Fortunedc397** [comment]
Same thing here bro

**Comment by Blackprosper** [comment]
> Same thing here bro

Same here bro, what's the solution now?
