### ISSUE TITLE
Deoply link isn't working,... please fix it 

### ISSUE THREAD

**Issue by bilalking99** [lyfe00011/whatsapp-bot-md#340]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Platform: [e.g. Heroku]
 - Version [e.g. 3.4.5]

**Additional context**

**Comment by JONESNJANE** [comment]
![Screenshot_20240127-075838](https://github.com/lyfe00011/whatsapp-bot-md/assets/138817141/112a326f-2add-44aa-aee5-baf5e85f71f0)
