### ISSUE TITLE
Feature request.... (you can ignore this as you are a busy guy) 

### ISSUE THREAD

**Issue by Ayushdeveloper001** [lyfe00011/whatsapp-bot-md#359]
So I wanted to request a feature and I tried a lot contacting you but it was not possible so I wanna ask if there can be a feature which can automatically send one time pictures/videos/vm in our dns without using /vv command and if it's possible that's gonna be the best update in the Lyfe bot after anti delete as we know only Lyfe is capable of making impossible things possible so if it is not necessary for you to add that feature we understand. Thanks

**Comment by lyfe00011** [comment]
https://gist.github.com/lyfe00011/7101f97d995d6268df99ccc3118daabf

**Comment by lyfe00011** [comment]
https://gist.github.com/lyfe00011/8f4cc76d99a49f36919934befe1d6507

**Comment by chyyps** [comment]
```---ERROR REPORT---

Version : 5.2.7
Message : /setvv p
Error   : failed_precondition
Jid     : 9100000000000@s.whatsapp.net
command : setvv
Platform : koyeb```

```-----``` *Made by LyFE with ❣* ```-----```
