### ISSUE TITLE
Can You Tell Useful Commands eg:#lastseen for AFK 

### ISSUE THREAD

**Issue by mrlinux007** [lyfe00011/whatsapp-bot-md#36]
@lyfe00011 ### 

- [x] _**Can You Tell Useful Commands eg:#lastseen for AFK**_

**Comment by lyfe00011** [comment]
> @lyfe00011 ###
> 
> * [x]  _**Can You Tell Useful Commands eg:#lastseen for AFK**_

https://github.com/lyfe00011/whatsapp-bot-md/wiki
