### ISSUE TITLE
Bot Does Not Respond User to FB Plugin

### ISSUE THREAD

**Issue by weskerty** [lyfe00011/whatsapp-bot-md#369]
**Describe the bug**
FB allowed for global use in a chat
The bot responds to the Facebook link but then requests the quality of the video; At this time the bot only accepts responses from usersudo

**To Reproduce**
1- Zushi FB Allow FB globally in group
2- That a normal user requests to download a video from Facebook. fb link
3- the normal user cannot choose the quality of the video and the bot does not send a response.

**Expected behavior**
Just like YTV where normal users can choose the quality of the video and the bot responds to the common user.

**Screenshots**
![Screenshot_1](https://github.com/lyfe00011/whatsapp-bot-md/assets/82781997/e492cba0-fa74-4343-9e1e-b0c3ed39d96c)

**Platform (please complete the following information):**
 - Platform: VPS
 - Version: 5.3.2

**Comment by lyfe00011** [comment]
add `zushi upload`
