### ISSUE TITLE
Add External Plugins Link to the Readme

### ISSUE THREAD

**Issue by weskerty** [lyfe00011/whatsapp-bot-md#372]
**Describe the bug**
The link for external plugins is sent only when you log in, it is not in the readme or in the plugins wiki.

**Expected behavior**
Adding the link to the Wiki or Readme would be useful to avoid having to force logout to be able to have the link again in case you have temporary messages.

**Comment by lyfe00011** [comment]
?

**Comment by weskerty** [comment]
I'm sorry I explained it wrong.
I can't find the "external plugins" link in the repository wiki.

I know the bot sends when it starts up for the first time, but I didn't want to log out and log in again.

**Comment by lyfe00011** [comment]
plugins link within start message
what `but I didn't want to log out and log in again`  ?

**Comment by weskerty** [comment]
Yes, the link is sent in the initial message, but it was deleted.
I just didn't want to log back into the bot to receive the message.
Can you give me the link?

**Comment by lyfe00011** [comment]
[plugins link](https://levanter-plugins.vercel.app/)

**Comment by tsep073** [comment]
Sure,can I fork the project or just make a replica of it?
