### ISSUE TITLE
App "bot name" not found (For most commands)

### ISSUE THREAD

**Issue by LorrdWealth** [lyfe00011/whatsapp-bot-md#392]
![Screenshot_2024-05-09-00-41-06-975_com.delta.jpg](https://github.com/lyfe00011/whatsapp-bot-md/assets/99515430/d37662a0-aa40-4309-8144-64b0879194de)

Most of the commands show that error. 
If I try to turn on auto reject call or turn it off, it says "app not found" too.

**Comment by lyfe00011** [comment]
check koyeb app name
