### ISSUE TITLE
Bot does not initialize (session restored frozen)

### ISSUE THREAD

**Issue by weskerty** [lyfe00011/whatsapp-bot-md#393]
**Describe the bug**
Scan and start the bot. It happens with default and custom ID.
I have made "force_logout=true" and when I log in again this error occurs.

I deleted database.db and messages.db and still the same "session restored" error appears and it stays frozen there indefinitely.

**To Reproduce**
1. Scan session
2. Start the bot

**Expected behavior**
Installing Plugins etc and start.

**Screenshots**
![image](https://github.com/lyfe00011/whatsapp-bot-md/assets/82781997/a7bc0508-4636-4470-bfe7-3ed648a1959c)

**Platform (please complete the following information):**
 - Platform: This Happens on Windows 10 Node 20 and Debian 11 Node 18
 - Version 5.4.2

**Comment by lyfe00011** [comment]
network issue?

**Comment by weskerty** [comment]
> network issue?

No. The rest of the things work. Other node services also work.
