### ISSUE TITLE
Can't send message to groups

### ISSUE THREAD

**Issue by ahmadkeren** [lyfe00011/whatsapp-bot-md#4]
As a fellow user of the bailyes module, has anyone experienced a message that couldn't be sent to a group?
Note: this problem occurs quite often, and does not occur in private messages

**Comment by lyfe00011** [comment]
> As a fellow user of the bailyes module, has anyone experienced a message that couldn't be sent to a group? Note: this problem occurs quite often, and does not occur in private messages

This is not Baileys repository 🌝
