### ISSUE TITLE
Bot not running on aws

### ISSUE THREAD

**Issue by amegh-ts** [lyfe00011/whatsapp-bot-md#475]
**Describe the bug**
Bot not starting on aws. Getting fix on log

**Screenshots**

**Platform (please complete the following information):**
 - Platform: AWS
![Screenshot (2)](https://github.com/user-attachments/assets/1e04e65a-dd78-4570-bff8-607fe1cec514)

**Comment by lyfe00011** [comment]
git pull origin master && yarn install
