### ISSUE TITLE
How Do i Add my Own plugin or atleast run a code and and send back response as message? have attached code in description

### ISSUE THREAD

**Issue by rnaikgaonkar** [lyfe00011/whatsapp-bot-md#481]
const { bot } = require('../lib')
const axios = require('axios')

bot(
  {
    pattern: 'ask ?(.*)',
    fromMe: true,
    desc: 'Ask Llama3 a question',
    type: 'AI',
  },
  async (message, match) => {
    match = match || message.reply_message.text
    if (!match) return await message.send('*Example : ask why is the sky blue?*')

    try {
      const response = await axios.post('http://localhost:11434/api/chat', {
        model: 'llama3',
        messages: [
          {
            role: 'user',
            content: match
          }
        ],
        stream: false
      })

      const { content } = response.data.message
      await message.send(content, { quoted: message.data })
    } catch (error) {
      await message.send('*There was an error processing your request.*')
    }
  }
)

**Comment by lyfe00011** [comment]
[create a gist](gist.github.com)

Use cmd _plugin_

**Comment by bencool-7398** [comment]
Just bug the bots repository
