### ISSUE TITLE
spam

### ISSUE THREAD

**Issue by SUHAID-BROO** [lyfe00011/whatsapp-bot-md#61]
Bro lyfe bot md spam aavunu karanm ntha 🙂this emoji

**Comment by lyfe00011** [comment]
> Bro lyfe bot md spam aavunu karanm ntha 🙂this emoji

Because you spam

**Comment by SUHAID-BROO** [comment]
Njan aadyam scan aaki pinne deploy" cheythu ennit worker on cheythappol aan
spam aavunnath enik ente numberil thanne aan spam aavunnath
