### ISSUE TITLE
How To Make Bot Public

### ISSUE THREAD

**Issue by AliyahBots** [lyfe00011/whatsapp-bot-md#62]

**Comment by Embheeyfta** [comment]
You can't make it public, you can only set who are allowed to use it by using command (.setsudo) replying to user, you can do manually in heroku,reveal vars, SUDO add user WhatsApp number and country code, remove the plus sign

**Comment by Leovichu** [comment]
> in

https://github.com/lyfe00011/whatsapp-bot-md/issues/62#issuecomment-1205861912

**Comment by Kannancomrade** [comment]
> You can't make it public, you can only set who are allowed to use it by using command (.setsudo) replying to user, you can do manually in heroku,reveal vars, SUDO add user WhatsApp number and country code, remove the plus sign

But we need the public can you add as public

**Comment by Embheeyfta** [comment]
Sorry, I am not the owner, but we wish to have in the next update

**Comment by Embheeyfta** [comment]
We can no longer deploy to HEROKU as they're busy deleting peoples
accounts, both new and old accounts, please find an alternative for us.
