### ISSUE TITLE
Send messages multiple times

### ISSUE THREAD

**Issue by Embheeyfta** [lyfe00011/whatsapp-bot-md#63]
The bot keep sending messages after command or tag, it will just keep answering the commands making it a spam, please fix it, thanks

**Comment by Kalakeyamodes** [comment]
😂

**Comment by Kalakeyamodes** [comment]
@Kalakeyamodes

**Comment by Kalakeyamodes** [comment]
> 

Tagall

**Comment by lyfe00011** [comment]
> The bot keep sending messages after command or tag, it will just keep answering the commands making it a spam, please fix it, thanks

screenshot ?

**Comment by BASHER0706** [comment]
> > The bot keep sending messages after command or tag, it will just keep answering the commands making it a spam, please fix it, thanks
> 
> screenshot ?

Do you have a whatsapp group, kindly share link

**Comment by lyfe00011** [comment]
> > > The bot keep sending messages after command or tag, it will just keep answering the commands making it a spam, please fix it, thanks
> > 
> > 
> > screenshot ?
> 
> Do you have a whatsapp group, kindly share link

https://chat.whatsapp.com/I703smlNtndJfksuxvitK9
