### ISSUE TITLE
How to crop video??

### ISSUE THREAD

**Issue by akhtarbalouch** [lyfe00011/whatsapp-bot-md#65]

**Comment by lyfe00011** [comment]
> _No description provided._

crop command out resolution and x,y coordinates to crop in video little weird but when get it ec

**Comment by akhtarbalouch** [comment]
Thank you very much for your support , i am sorry if i disturbed you i have opened 2 issues today , but can you give me an example command of crop video , i have tried .crop x, .crop y , not understandable for me 🤔🥰
