### ISSUE TITLE
pm blocker

### ISSUE THREAD

**Issue by zZyreXx** [lyfe00011/whatsapp-bot-md#87]
pm blocker is not working pls fix it

**Comment by lyfe00011** [comment]
> pm blocker is not working pls fix it

https://gist.github.com/fasilvkn/0005cda7f7bd7238826be121d0e1c0b0/raw

**Comment by zZyreXx** [comment]
> > pm blocker is not working pls fix it
> 
> https://gist.github.com/fasilvkn/0005cda7f7bd7238826be121d0e1c0b0/raw
this plugin is showing err

**Comment by lyfe00011** [comment]
> > > pm blocker is not working pls fix it
> > 
> > 
> > https://gist.github.com/fasilvkn/0005cda7f7bd7238826be121d0e1c0b0/raw
> > this plugin is showing err

ss?

**Comment by Akku7897** [comment]
I could no deploy what is the issue

**Comment by Akku7897** [comment]
![Screenshot_20220829-095401_Chrome.jpg](https://user-images.githubusercontent.com/111695214/187122908-5d507b08-c567-4cfa-a90b-9e94f33e1887.jpg)

**Comment by lyfe00011** [comment]
> ![Screenshot_20220829-095401_Chrome.jpg](https://user-images.githubusercontent.com/111695214/187122908-5d507b08-c567-4cfa-a90b-9e94f33e1887.jpg)

Maybe you not forked repo or wrong username

**Comment by Akku7897** [comment]
Ok bro
